# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.llmRequestRouter.backendRouter.enabled .Values.llmRequestRouter.backendRouter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-request-router.backendRouterServiceAccountName" . }}
  namespace: {{ include "llm-request-router.namespace" . }}
  labels:
    {{- include "llm-request-router.backendRouterLabels" . | nindent 4 }}
  {{- with .Values.llmRequestRouter.backendRouter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
